# The URL the site will be built for
title = "NICHOLAS SHAW"
base_url = "https://nshaw.ca"
description = "Restaurant at the end of the universe."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Set theme name as folder inside /themes
theme = "zola-bearblog"


taxonomies = [
  {name = "categories", feed = true},
  {name = "tags", feed = true},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]
# Put all your custom variables here
date_format="%Y %b %d"

[[extra.main_menu]]
name = "posts"
url = "@/posts/_index.md"

[[extra.main_menu]]
name = "cv"
url = "@/cv.md"

[[extra.main_menu]]
name = "about"
url = "@/about.md"