name: Deploy to GCR
on:
  push:
    branches:
      - deploy/gh-action-gcr
jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: RafikFarhad/push-to-gcr-github-action@v5-rc1
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: gcr.io
          project_id: ${{ secrets.GCLOUD_BLOG_PROJECT_ID }}
          image_name: nshawca-webserver
          image_tag: latest
          dockerfile: ./Dockerfile
